Repository GreenSpaceStation/space-station-14-green, pull requests merged in 2025-09, with the labels that each got.

#34 Station goals
  Content.Server/GameTicking/GameTicker.RoundFlow.cs
  Content.Server/_Green/StationGoal/Commands/SendStationGoalCommand.cs
  Content.Server/_Green/StationGoal/Commands/SetSendStationGoalCommand.cs
  Content.Server/_Green/StationGoal/SendStationGoalsEvent.cs
  Content.Server/_Green/StationGoal/StationGoalComponent.cs
  Content.Server/_Green/StationGoal/StationGoalSystem.cs
  Content.Shared/Fax/Components/FaxMachineComponent.cs
  Content.Shared/_Green/StationGoal/StationGoalPrototype.cs
  Resources/Locale/ru-RU/_green/station-goals/dormitories.ftl
  Resources/Locale/ru-RU/_green/station-goals/energy.ftl
  Resources/Locale/ru-RU/_green/station-goals/form.ftl
  Resources/Locale/ru-RU/_green/station-goals/shuttle.ftl
  Resources/Prototypes/Entities/Structures/Machines/fax_machine.yml
  Resources/Prototypes/_Green/station_goals.yml
Labels: size/M, S: Needs Review, S: Untriaged

#36 Config fix
  Resources/ConfigPresets/Central/central.toml
Labels: Changes: No C#, S: Untriaged

#37 Карты, карты, карты
  Resources/Maps/Corvax/corvax_outpost.yml
  Resources/Maps/Corvax/corvax_pearl.yml
  Resources/Maps/_Green/GreenMaus.yml
  Resources/Maps/_Green/GreenPaper.yml
  Resources/Maps/_Green/GreenReach.yml
  Resources/Maps/_Green/GreenTushkan.yml
  Resources/Prototypes/_Green/Maps/Pools/green.yml
  Resources/Prototypes/_Green/Maps/maus.yml
  Resources/Prototypes/_Green/Maps/paper.yml
  Resources/Prototypes/_Green/Maps/reach.yml
  Resources/Prototypes/_Green/Maps/tushkan.yml
Labels: Changes: Map, Changes: No C#, size/XL, S: Needs Review

#39 Fixes
  Content.Server/Administration/Managers/BanManager.cs
  Content.Server/Connection/ConnectionManager.cs
  Content.Shared/DetailExaminable/DetailExaminableystem.cs
  Resources/Locale/ru-RU/_green/detail-examinable/detail-examinable.ftl
Labels: size/S, S: Needs Review, S: Untriaged
